---
title: "Stocks"
author: "Horacio Ballinas"
date: "11/20/2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plotly Example

The objective of this program is to download data from finance.yahoo.com through the quantomod package and plot the information using plotly

```{r, echo=FALSE}

library(plotly)
library(quantmod)


#Download data

getSymbols("AAPL",src='yahoo')
getSymbols("GOOGL",src='yahoo')
```

## Plots


```{r, echo=FALSE}
# Decompose the plots
df.aapl <- data.frame(Date=index(AAPL),coredata(AAPL)) #Decompose XTS object

# annotation
a <- list(text = "Stock Split",
          x = '2014-06-06',
          y = 1.02,
          xref = 'x',
          yref = 'paper',
          xanchor = 'left',
          showarrow = FALSE
)

# use shapes to create a line
l <- list(type = line,
          x0 = '2014-06-06',
          x1 = '2014-06-06',
          y0 = 0,
          y1 = 1,
          xref = 'x',
          yref = 'paper',
          line = list(color = 'black',
                      width = 0.5)
)

p <- df.aapl %>%
  plot_ly(x = ~Date, type="candlestick",
          open = ~AAPL.Open, close = ~AAPL.Close,
          high = ~AAPL.High, low = ~AAPL.Low) %>%
  layout(title = "Apple Stock",
         annotations = a,
         shapes = l)

p


```

```{r, echo=FALSE}

df.goog <- data.frame(Date=index(GOOGL),coredata(GOOGL)) #Decompose XTS object

# annotation
a <- list(text = "Stock Split",
          x = '2014-04-01',
          y = 1.02,
          xref = 'x',
          yref = 'paper',
          xanchor = 'left',
          showarrow = FALSE
)

# use shapes to create a line
l <- list(type = line,
          x0 = '2014-04-01',
          x1 = '2014-04-01',
          y0 = 0,
          y1 = 1,
          xref = 'x',
          yref = 'paper',
          line = list(color = 'black',
                      width = 0.5)
)

q <- df.goog %>%
  plot_ly(x = ~Date, type="candlestick",
          open = ~GOOGL.Open, close = ~GOOGL.Close,
          high = ~GOOGL.High, low = ~GOOGL.Low) %>%
  layout(title = "Google Stock",
         annotations = a,
         shapes = l)

q
```

